version: '3.2'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - '4563-4599:4563-4599'
      - '8055:8081'
    env_file:
      - .env
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./docker/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      - .env
  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - '3000:3000'
    platform: linux/amd64  
  vessel_tracker:
    build: ./docker/vessel_tracker
    container_name: vessel_tracker
    depends_on:
      - mongo
    command: python /src/ais_listner.py
    env_file:
      - .env

